### ISSUE TITLE
Create tablet definition for HP Pavilion x360 Convertible 14-CD0087TU (ELAN )

### ISSUE THREAD

**Issue by avinal** [linuxwacom/libwacom#404]
**Device name**
HP Pavilion x360 Convertible 14-CD0087TU

**Device model identifier**
14-CD0087TU

**udevadm info output**

*(What is this last thing?, please help)*

Reference: https://github.com/linuxwacom/wacom-hid-descriptors/issues/155

**Comment by whot** [comment]
> (What is this last thing?, please help)

`udevadm info /sys/class/input/eventXX` where `eventXX` is the event node of your tablet device. 

#405 should fix this, can you give it a try please?

**Comment by avinal** [comment]
Thanks a lot @whot,  it does work now I can see the tablet settings, the stylus works but still not shown in the GUI. Is this expected behavior. Or if I need to change some configs, please let me know. I have attached a clip for reference. 

https://user-images.githubusercontent.com/74113200/121302164-e7c76500-c916-11eb-9a2b-96e3a3bde0d2.mp4

**Comment by whot** [comment]
Does it work if you add

```
Styli=0xffffd
```
To the existing `[General]` section?

**Comment by avinal** [comment]
Nope still does not work. I added the line and ran `libwacom-update-db` and then restarted my computer

**Comment by whot** [comment]
If you run `libwacom-list-local-devices` does it show the device including the stylus line? If so, the libwacom part of this is correct and the problem is somewhere in the control panel.

**Comment by avinal** [comment]
Nope it does not, is the spelling `Styli` correct?
![image](https://user-images.githubusercontent.com/74113200/122787200-b796a380-d2d2-11eb-989f-c7528fd871d4.png)

**Comment by whot** [comment]
huh, I forgot I recently changed the output for that and it doesn't show the styli by default: `libwacom-list-local-devices --format=datafile` should do the trick.

**Comment by avinal** [comment]
Yepp, visible now.
